diskdelivery/cardapios/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('diskdelivery.cardapios.views',

    url(r'^novo/$', 'itemcardapio_novo', name='itemcardapio_novo'),
    url(r'^editar/(?P<item_id>\d+)/$', 'itemcardapio_editar', name='itemcardapio_editar'),
    url(r'^meu_cardapio/$','cardapio_lista', name='cardapio_lista'),

)

diskdelivery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'diskdelivery.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'login/','django.contrib.auth.views.login',{"template_name":"login.html"},name='login'),
    url(r'logout/','django.contrib.auth.views.logout_then_login',{'login_url': '/'},name='logout'),

    url(r'^$', 'diskdelivery.core.views.inicio_site', name='inicio_site'),
    url(r'^carregar/$', 'diskdelivery.core.views.carregar', name='carregar'),
    url(r'^home/$', 'diskdelivery.core.views.home', name='home'),


    url(r'^comidas/',include('diskdelivery.comidas.urls',namespace='comidas')),
    url(r'^cardapios/',include('diskdelivery.cardapios.urls',namespace='cardapios')),
    url(r'^restaurantes/',include('diskdelivery.restaurantes.urls',namespace='restaurantes')),

    url(r'^clientes/',include('diskdelivery.clientes.urls',namespace='clientes')),
    url(r'^cadastro/$', 'diskdelivery.clientes.views.cadastro', name='cadastro'),
)

diskdelivery/cardapios/models.py
#coding:utf-8
from django.db import models
from diskdelivery.comidas.models import Comida
from diskdelivery.restaurantes.models import Restaurante
# Create your models here.

class ItemCardapio(models.Model):
	restaurante = models.ForeignKey(Restaurante,blank=True,null=True)
	nome = models.CharField(max_length=100)
	descricao = models.CharField(max_length=100,blank=True,null=True)
	preco = models.DecimalField(default=0.0,max_digits=10,decimal_places=2)
	comida = models.ForeignKey(Comida)

diskdelivery/cardapios/forms.py
# coding: utf-8

from django import forms
from diskdelivery.cardapios.models import ItemCardapio
from diskdelivery.comidas.models import Comida
from diskdelivery.restaurantes.models import Restaurante
from django.core.exceptions import ValidationError
from django.forms.widgets import Select

class ItemCardapioForm(forms.ModelForm):
    class Meta:
        model = ItemCardapio
        fields = ('nome','descricao','preco','comida')
        widgets ={
        	'nome': forms.TextInput(attrs={'class':'form-control','size':30}),
            'descricao': forms.Textarea(attrs={'class':'form-control','size':30}),
            'preco': forms.TextInput(attrs={'class':'form-control','size':30}),
            'comida': Select(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(ItemCardapioForm, self).__init__(*args, **kwargs)  
        restaurante = Restaurante.objects.get(id=kwargs['initial']['restaurante_id'])
        self.fields['comida'].queryset = restaurante.comidas


    def clean_nome(self):
        '''
            @clean_name: Transforma o nome em maiusculo
        '''
        return self.cleaned_data['nome'].upper()

diskdelivery/cardapios/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import user_passes_test,login_required
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse as r
from diskdelivery.cardapios.models import ItemCardapio
from diskdelivery.cardapios.forms import ItemCardapioForm
from diskdelivery.restaurantes.models import Restaurante

def cardapio_lista(request):
	'''
		@View para renderizar o cardapio de um restaurante
	'''

	restaurante = Restaurante.objects.get(id=request.user.id)

	cardapio = ItemCardapio.objects.filter(restaurante=restaurante)
	return render(request,"cardapio_lista.html",{'cardapio':cardapio,'restaurante':restaurante})

def itemcardapio_novo(request):
	'''
		@comida_nova: View para cadastrar um novo tipo de comida
	'''
	restaurante = Restaurante.objects.get(id=request.user.id)
	
	if request.method == 'POST':
		form = ItemCardapioForm(request.POST,initial={'restaurante_id':restaurante.id})
		if form.is_valid():
			obj = form.save(commit=False)
			obj.restaurante = restaurante
			obj.save()
			return HttpResponseRedirect(r('cardapios:cardapio_lista'))
		return render(request,"item_cardapio_novo.html",{'form':form})
	else:
		return render(request,"item_cardapio_novo.html",{'form':ItemCardapioForm(initial={'restaurante_id': restaurante.id})})
	
def itemcardapio_editar(request,item_id):
	'''
		@comid_editar: View para editar os dados de uma comida
	'''
	item = get_object_or_404(ItemCardapio,id=item_id)
	restaurante = Restaurante.objects.get(id=request.user.id)
	if request.method == 'POST':
		form = ItemCardapioForm(request.POST,instance=item,initial={'restaurante_id':restaurante.id})
		if form.is_valid():
			obj = form.save(commit=False)
			obj.restaurante = restaurante
			obj.save()
			return HttpResponseRedirect(r('cardapios:cardapio_lista'))
		return render(request,"item_cardapio_editar.html",{'form':form})
	else:
		return render(request,"item_cardapio_editar.html",{'form':ItemCardapioForm(instance=item,initial={'restaurante_id':restaurante.id})})

diskdelivery/cardapios/templates/cardapio_lista.html
{% extends 'base.html' %}
{%block content%}
<div class="bs-callout bs-callout-danger">
  <h4>Carápio do restaurante: {{restaurante}}</h4>
</div>
<a class="btn btn-warning" href="{% url 'cardapios:itemcardapio_novo' %}">Novo</a>

<br/><br/>
<div class="panel-body">
          <div class="adv-table">
              <table class="table table-bordered table-striped" id="hidden-table-info">
                 <thead>
                <tr>
                    <th class="td-edit">Editar</th>
                    <th class="td-edit">Tipo</th>
                    <th class="td-edit">Preço</th>
                    <th>Nome</th>
                </tr>
              </thead>
              <tbody>
                {%for c in cardapio%}
                    <tr>
                        <td class="td-edit"><a href="{% url 'cardapios:itemcardapio_editar' item_id=c.id%}"><i class="fa fa-pencil-square-o "></a></td>
                        <td class="td-edit">{{c.comida}}</td>
                        <td class="td-edit">{{c.preco}}</td>
                        <td>{{c.nome}}</td>
                    </tr>
                {%endfor%}
              
              </tbody>
              </table>

          </div>
    </div>

  <script src="{{ STATIC_URL }}js/jquery.dataTables.js" type="text/javascript" ></script>
  <script src="{{ STATIC_URL }}js/DT_bootstrap.js" type="text/javascript" ></script>

        <script type="text/javascript">
          /* Formating function for row details */

         $(document).ready(function() {
              var oTable = $('#hidden-table-info').dataTable( {
                  "aoColumnDefs": [
                      { "bSortable": false, "aTargets": [ 0 ] }
                  ],
                  "aaSorting": [[1, 'asc']]
              });

          } );
      </script>
{%endblock%}

diskdelivery/cardapios/templates/item_cardapio_editar.html
{% extends 'base.html' %}
{%block content%}
<link href="{{ STATIC_URL }}css/cliente.css" rel="stylesheet" type="text/css" />

<ul class="breadcrumb">
    <li><a href="/">Inicio</a> <span class="divider"></span></li>
    <li><a href="{% url 'cardapios:cardapio_lista' %}">Meu cardápio</a></li>
    <li class="active">Item Novo para o Cardápio</li>
</ul>

<div class="bs-callout bs-callout-danger">
  <h4>Item novo para o cardápio</h4>
</div>
<form class="form-inline" method="POST" >
    {% csrf_token %}            
    {{form.as_p}}
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
{%endblock%}

diskdelivery/cardapios/templates/item_cardapio_novo.html
{% extends 'base.html' %}
{%block content%}
<link href="{{ STATIC_URL }}css/cliente.css" rel="stylesheet" type="text/css" />

<ul class="breadcrumb">
    <li><a href="/">Inicio</a> <span class="divider"></span></li>
    <li><a href="{% url 'cardapios:cardapio_lista' %}">Meu cardápio</a></li>
    <li class="active">Item Novo para o Cardápio</li>
</ul>

<div class="bs-callout bs-callout-danger">
  <h4>Item novo para o cardápio</h4>
</div>
<form class="form-inline" method="POST" >
    {% csrf_token %}            
    {{form.as_p}}
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
{%endblock%}