diskdelivery/comidas/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('diskdelivery.comidas.views',

    url(r'^novo/$', 'comida_nova', name='comida_nova'),
    url(r'^editar/(?P<comida_id>\d+)/$', 'comida_editar', name='comida_editar'),
    url(r'^lista/$','comida_lista', name='comida_lista'),

)

diskdelivery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'diskdelivery.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'login/','django.contrib.auth.views.login',{"template_name":"login.html"},name='login'),
    url(r'logout/','django.contrib.auth.views.logout_then_login',{'login_url': '/'},name='logout'),

    url(r'^$', 'diskdelivery.core.views.inicio_site', name='inicio_site'),
    url(r'^carregar/$', 'diskdelivery.core.views.carregar', name='carregar'),
    url(r'^home/$', 'diskdelivery.core.views.home', name='home'),


    url(r'^comidas/',include('diskdelivery.comidas.urls',namespace='comidas')),
    url(r'^cardapios/',include('diskdelivery.cardapios.urls',namespace='cardapios')),
    url(r'^restaurantes/',include('diskdelivery.restaurantes.urls',namespace='restaurantes')),

    url(r'^clientes/',include('diskdelivery.clientes.urls',namespace='clientes')),
    url(r'^cadastro/$', 'diskdelivery.clientes.views.cadastro', name='cadastro'),
)

diskdelivery/comidas/models.py
#coding:utf-8
from django.db import models

# Create your models here.

class Comida(models.Model):
    nome = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nome

diskdelivery/comidas/forms.py
# coding: utf-8

from django import forms
from diskdelivery.comidas.models import Comida
from django.core.exceptions import ValidationError

class ComidaForm(forms.ModelForm):
    class Meta:
        model = Comida
        fields = ('nome',)
        widgets ={
        	'nome': forms.TextInput(attrs={'class':'form-control','size':30}),
        }

    def clean_nome(self):
        '''
            @clean_name: Transforma o nome em maiusculo
        '''
        return self.cleaned_data['nome'].upper()

diskdelivery/comidas/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import user_passes_test,login_required
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse as r
from diskdelivery.comidas.models import Comida
from diskdelivery.comidas.forms import ComidaForm


def comida_lista(request):

	return render(request,"comida_lista.html",{'comidas':Comida.objects.all().order_by('nome')})

def comida_nova(request):
	'''
		@comida_nova: View para cadastrar um novo tipo de comida
	'''

	if request.method == 'POST':
		form = ComidaForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			return HttpResponseRedirect(r('comidas:comida_lista'))
		return render(request,"comida_nova.html",{'form':form})
	else:
		return render(request,"comida_nova.html",{'form':ComidaForm()})
	
def comida_editar(request,comida_id):
	'''
		@comid_editar: View para editar os dados de uma comida
	'''
	comida = get_object_or_404(Comida,id=comida_id)
	if request.method == 'POST':
		form = ComidaForm(request.POST,instance=comida)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			return HttpResponseRedirect(r('comidas:comida_lista'))
		return render(request,"comida_editar.html",{'form':form})
	else:
		return render(request,"comida_editar.html",{'form':ComidaForm(instance=comida)})

diskdelivery/comidas/templates/comida_editar.html
{% extends 'base.html' %}
{%block content%}
<link href="{{ STATIC_URL }}css/cliente.css" rel="stylesheet" type="text/css" />

<ul class="breadcrumb">
    <li><a href="/">Inicio</a> <span class="divider"></span></li>
    <li><a href="{% url 'comidas:comida_lista' %}">Lista de Comidas</a></li>
    <li class="active">Editar</li>
</ul>

<div class="bs-callout bs-callout-danger">
  <h4>Editar</h4>
</div>
<form class="form-inline" method="POST" >
    {% csrf_token %}            
    <label>{{form.nome.label}} :</label>{{form.nome}}{{form.nome.errors}}</p>
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
{%endblock%}

diskdelivery/comidas/templates/comida_lista.html
{% extends 'base.html' %}
{%block content%}
<div class="bs-callout bs-callout-danger">
  <h4>Todos os tipos de comida</h4>
</div>
<a class="btn btn-warning" href="{% url 'comidas:comida_nova' %}">Novo</a>

<br/><br/>
<div class="panel-body">
          <div class="adv-table">
              <table class="table table-bordered table-striped" id="hidden-table-info">
                 <thead>
                <tr>
                    <th class="td-edit">Editar</th>
                    <th>Nome</th>
                </tr>
              </thead>
              <tbody>
                {%for c in comidas%}
                    <tr>
                        <td class="td-edit"><a href="{% url 'comidas:comida_editar' comida_id=c.id %}"><i class="fa fa-pencil-square-o "></a></td>
                        <td>{{c.nome}}</td>
                    </tr>
                {%endfor%}
              
              </tbody>
              </table>

          </div>
    </div>

  <script src="{{ STATIC_URL }}js/jquery.dataTables.js" type="text/javascript" ></script>
  <script src="{{ STATIC_URL }}js/DT_bootstrap.js" type="text/javascript" ></script>

        <script type="text/javascript">
          /* Formating function for row details */

         $(document).ready(function() {
              var oTable = $('#hidden-table-info').dataTable( {
                  "aoColumnDefs": [
                      { "bSortable": false, "aTargets": [ 0 ] }
                  ],
                  "aaSorting": [[0, 'asc']]
              });

          } );
      </script>
{%endblock%}

diskdelivery/comidas/templates/comida_nova.html
{% extends 'base.html' %}
{%block content%}
<link href="{{ STATIC_URL }}css/cliente.css" rel="stylesheet" type="text/css" />

<ul class="breadcrumb">
    <li><a href="/">Inicio</a> <span class="divider"></span></li>
    <li><a href="{% url 'comidas:comida_lista' %}">Lista de Comidas</a></li>
    <li class="active">Comida Nova</li>
</ul>

<div class="bs-callout bs-callout-danger">
  <h4>Comida nova</h4>
</div>
<form class="form-inline" method="POST" >
    {% csrf_token %}            
    <label>{{form.nome.label}} :</label>{{form.nome}}{{form.nome.errors}}</p>
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
{%endblock%}