diskdelivery/restaurantes/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('diskdelivery.restaurantes.views',

    url(r'^novo/$', 'restaurante_novo', name='restaurante_novo'),
    url(r'^editar/(?P<restaurante_id>\d+)/$', 'restaurante_editar', name='restaurante_editar'),
    url(r'^lista/$','restaurante_lista', name='restaurante_lista'),
)

diskdelivery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'diskdelivery.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'login/','django.contrib.auth.views.login',{"template_name":"login.html"},name='login'),
    url(r'logout/','django.contrib.auth.views.logout_then_login',{'login_url': '/'},name='logout'),

    url(r'^$', 'diskdelivery.core.views.inicio_site', name='inicio_site'),
    url(r'^carregar/$', 'diskdelivery.core.views.carregar', name='carregar'),
    url(r'^home/$', 'diskdelivery.core.views.home', name='home'),


    url(r'^comidas/',include('diskdelivery.comidas.urls',namespace='comidas')),
    url(r'^cardapios/',include('diskdelivery.cardapios.urls',namespace='cardapios')),
    url(r'^restaurantes/',include('diskdelivery.restaurantes.urls',namespace='restaurantes')),

    url(r'^clientes/',include('diskdelivery.clientes.urls',namespace='clientes')),
    url(r'^cadastro/$', 'diskdelivery.clientes.views.cadastro', name='cadastro'),
)

diskdelivery/restaurantes/models.py
#coding:utf-8
from django.db import models
from diskdelivery.core.models import Pessoa
from diskdelivery.comidas.models import Comida
# Create your models here.

class Restaurante(Pessoa):
	razao_social = models.CharField(max_length=100,verbose_name="Razão Social")
	cnpj = models.CharField(max_length=14,blank=True,null=True)
	comidas = models.ManyToManyField(Comida)

	def __unicode__(self):
		return self.razao_social

diskdelivery/restaurantes/forms.py
# coding: utf-8

from django import forms
from diskdelivery.restaurantes.models import Restaurante
from django.core.exceptions import ValidationError

class RestauranteForm(forms.ModelForm):
    class Meta:
        model = Restaurante
        fields = ('razao_social','email','telefone','endereco','bairro','municipio','estado','cnpj','password','comidas')
        widgets ={
        	'razao_social': forms.TextInput(attrs={'class':'form-control','size':30}),
            'email': forms.TextInput(attrs={'class':'form-control','size':30}),
            'telefone': forms.TextInput(attrs={'class':'form-control','size':30}),
            'endereco': forms.TextInput(attrs={'class':'form-control','size':30}),
            'bairro': forms.TextInput(attrs={'class':'form-control','size':30}),
            'municipio': forms.TextInput(attrs={'class':'form-control','size':30}),
            'estado': forms.TextInput(attrs={'class':'form-control','size':30}),
            'cnpj': forms.TextInput(attrs={'class':'form-control','size':30}),
            'password': forms.TextInput(attrs={'class':'form-control','size':30}),
            'comidas': forms.CheckboxSelectMultiple(attrs={'class':'form-inline'}),
        }

    def clean_nome(self):
        '''
            @clean_name: Transforma o nome em maiusculo
        '''
        return self.cleaned_data['nome'].upper()


class RestauranteFormEditar(forms.ModelForm):
    class Meta:
        model = Restaurante
        fields = ('razao_social','email','telefone','endereco','bairro','municipio','estado','cnpj','comidas')
        widgets ={
            'razao_social': forms.TextInput(attrs={'class':'form-control','size':30}),
            'email': forms.TextInput(attrs={'class':'form-control','size':30}),
            'telefone': forms.TextInput(attrs={'class':'form-control','size':30}),
            'endereco': forms.TextInput(attrs={'class':'form-control','size':30}),
            'bairro': forms.TextInput(attrs={'class':'form-control','size':30}),
            'municipio': forms.TextInput(attrs={'class':'form-control','size':30}),
            'estado': forms.TextInput(attrs={'class':'form-control','size':30}),
            'cnpj': forms.TextInput(attrs={'class':'form-control','size':30}),
            'comidas': forms.CheckboxSelectMultiple(attrs={'class':'form-inline'}),
        }

    def clean_nome(self):
        '''
            @clean_name: Transforma o nome em maiusculo
        '''
        return self.cleaned_data['nome'].upper()

diskdelivery/restaurantes/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import user_passes_test,login_required
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse as r
from django.contrib.auth.models import Group
from diskdelivery.restaurantes.forms import RestauranteForm,RestauranteFormEditar
from diskdelivery.restaurantes.models import Restaurante


def restaurante_lista(request):

	return render(request,"restaurante_lista.html",{'restaurantes':Restaurante.objects.all()})

def restaurante_novo(request):
	'''
		@restaurante_novo: View para cadastrar um novo restaurante
	'''
	if request.method == 'POST':
		 form = RestauranteForm(request.POST)
		 if form.is_valid():
		 	obj = form.save(commit=False)
		 	obj.username = obj.email
		 	obj.set_password(obj.password)
		 	grupo = Group.objects.get(name='Restaurante')
		 	obj.save()
		 	obj.groups.add(grupo)
		 	obj.save()
		 	return HttpResponseRedirect(r('restaurantes:restaurante_lista'))
		 return render(request,"restaurante_novo.html",{'form':form})
	else:
		return render(request,"restaurante_novo.html",{'form':RestauranteForm()})


def restaurante_editar(request,restaurante_id):
	'''
		@restaurante_editar: view para editar os dados de um restaurante
	'''

	restaurante = get_object_or_404(Restaurante,id=restaurante_id)
	if request.method == 'POST':
		form = RestauranteFormEditar(request.POST,instance=restaurante)
		if form.is_valid():
			obj = form.save(commit=False)
		 	obj.save()
		 	form.save_m2m()
		 	return HttpResponseRedirect(r('restaurantes:restaurante_lista'))
		return render(request,"restaurante_editar.html",{'form':form})
	else:
		return render(request,"restaurante_editar.html",{'form':RestauranteFormEditar(instance=restaurante)})

diskdelivery/restaurantes/templates/restaurante_editar.html
{% extends 'base.html' %}
{%block content%}
<link href="{{ STATIC_URL }}css/cliente.css" rel="stylesheet" type="text/css" />

<ul class="breadcrumb">
    <li><a href="/">Inicio</a> <span class="divider"></span></li>
    <li><a href="{% url 'restaurantes:restaurante_lista' %}">Lista de Restaurantes</a></li>
    <li class="active">Editar Restaurante</li>
</ul>

<div class="bs-callout bs-callout-danger">
  <h4>Editar Restaurante</h4>
</div>
<form class="form-inline" method="POST" >
    {% csrf_token %}            
    {{form.as_p}}
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
{%endblock%}

diskdelivery/restaurantes/templates/restaurante_lista.html
{% extends 'base.html' %}
{%block content%}
<div class="bs-callout bs-callout-danger">
  <h4>Todos os restaurantes</h4>
</div>
<a class="btn btn-warning" href="{% url 'restaurantes:restaurante_novo' %}">Novo</a>

<br/><br/>
<div class="panel-body">
          <div class="adv-table">
              <table class="table table-bordered table-striped" id="hidden-table-info">
                 <thead>
                <tr>
                    <th class="td-edit">Editar</th>
                    <th>Nome</th>
                </tr>
              </thead>
              <tbody>
                {%for r in restaurantes%}
                    <tr>
                        <td class="td-edit"><a href="{% url 'restaurantes:restaurante_editar' restaurante_id=r.id%}"><i class="fa fa-pencil-square-o "></a></td>
                        <td>{{r.razao_social}}</td>
                    </tr>
                {%endfor%}
              
              </tbody>
              </table>

          </div>
    </div>

  <script src="{{ STATIC_URL }}js/jquery.dataTables.js" type="text/javascript" ></script>
  <script src="{{ STATIC_URL }}js/DT_bootstrap.js" type="text/javascript" ></script>

        <script type="text/javascript">
          /* Formating function for row details */

         $(document).ready(function() {
              var oTable = $('#hidden-table-info').dataTable( {
                  "aoColumnDefs": [
                      { "bSortable": false, "aTargets": [ 0 ] }
                  ],
                  "aaSorting": [[1, 'asc']]
              });

          } );
      </script>
{%endblock%}

diskdelivery/restaurantes/templates/restaurante_novo.html
{% extends 'base.html' %}
{%block content%}
<link href="{{ STATIC_URL }}css/cliente.css" rel="stylesheet" type="text/css" />

<ul class="breadcrumb">
    <li><a href="/">Inicio</a> <span class="divider"></span></li>
    <li><a href="{% url 'restaurantes:restaurante_lista' %}">Lista de Restaurantes</a></li>
    <li class="active">Restaurante Novo</li>
</ul>

<div class="bs-callout bs-callout-danger">
  <h4>Restaurante Novo</h4>
</div>
<form class="form-inline" method="POST" >
    {% csrf_token %}            
    {{form.as_p}}
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
{%endblock%}