diskdelivery/cardapios/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('diskdelivery.cardapios.views',

    url(r'^novo/$', 'itemcardapio_novo', name='itemcardapio_novo'),
    url(r'^editar/(?P<item_id>\d+)/$', 'itemcardapio_editar', name='itemcardapio_editar'),
    url(r'^meu_cardapio/$','cardapio_lista', name='cardapio_lista'),

)

diskdelivery/comidas/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('diskdelivery.comidas.views',

    url(r'^novo/$', 'comida_nova', name='comida_nova'),
    url(r'^editar/(?P<comida_id>\d+)/$', 'comida_editar', name='comida_editar'),
    url(r'^lista/$','comida_lista', name='comida_lista'),

)

diskdelivery/restaurantes/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('diskdelivery.restaurantes.views',

    url(r'^novo/$', 'restaurante_novo', name='restaurante_novo'),
    url(r'^editar/(?P<restaurante_id>\d+)/$', 'restaurante_editar', name='restaurante_editar'),
    url(r'^lista/$','restaurante_lista', name='restaurante_lista'),
)

diskdelivery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'diskdelivery.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'login/','django.contrib.auth.views.login',{"template_name":"login.html"},name='login'),
    url(r'logout/','django.contrib.auth.views.logout_then_login',{'login_url': '/'},name='logout'),

    url(r'^$', 'diskdelivery.core.views.inicio_site', name='inicio_site'),
    url(r'^carregar/$', 'diskdelivery.core.views.carregar', name='carregar'),
    url(r'^home/$', 'diskdelivery.core.views.home', name='home'),


    url(r'^comidas/',include('diskdelivery.comidas.urls',namespace='comidas')),
    url(r'^cardapios/',include('diskdelivery.cardapios.urls',namespace='cardapios')),
    url(r'^restaurantes/',include('diskdelivery.restaurantes.urls',namespace='restaurantes')),

    url(r'^clientes/',include('diskdelivery.clientes.urls',namespace='clientes')),
    url(r'^cadastro/$', 'diskdelivery.clientes.views.cadastro', name='cadastro'),
)

diskdelivery/core/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User,Group


class Pessoa(User):
    '''
        @Pessoa: Modelo para uma nova pessoa
    ''' 
    telefone            = models.CharField(max_length=11,blank=True,null=True)
    endereco            = models.CharField(max_length=30,blank=True,null=True,verbose_name='Endereço')
    bairro              = models.CharField(max_length=20,blank=True,null=True)
    municipio           = models.CharField(max_length=20,blank=True,null=True)
    estado              = models.CharField(max_length=20,blank=True,null=True)
    grupo               = models.ForeignKey(Group,blank=True,null=True)

    def __unicode__(self):
        return self.first_name

diskdelivery/core/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse as r
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import user_passes_test,login_required
from django.contrib.auth.models import Group,User

from diskdelivery.core.models import Pessoa

def inicio_site(request):
	'''
		@inicio_site: View para renderizar a página inicial do site
	'''
	return render(request,"inicio_site.html")

@login_required
def home(request):
	'''
		@home: View para acesso da interface adminsitrativa
	'''

	usuario = request.user
	try:
		usuario = Pessoa.objects.get(id=request.user.id)
	except:
		pass

	return render(request,"home.html",{'pessoa':usuario})

def carregar(request):

    grupo_admin = Group.objects.create(name='Administrador')
    grupo_restaurante = Group.objects.create(name='Restaurante')
    grupo_cliente = Group.objects.create(name='Cliente')

    return HttpResponse("gerado")

diskdelivery/core/templates/base.html
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">		


	<script src="{{ STATIC_URL }}js/jquery-2.0.0.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>        
    <script src="{{ STATIC_URL }}js/jquery-ui-1.10.2.min.js"></script>    
    <script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-datepicker.pt-BR.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.maskedinput.js"></script>
    <script src="{{ STATIC_URL }}js/bootbox.min.js"></script>
    <link href="{{ STATIC_URL }}css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
	<link href="{{STATIC_URL}}css/style.css" rel="stylesheet">
	<link href="{{STATIC_URL}}css/topo.css" rel="stylesheet">
	<link href="{{STATIC_URL}}css/principal.css" rel="stylesheet">
	<link href="{{STATIC_URL}}css/pagination.css" rel="stylesheet">

</head>

<body class="front scroll-spy">
	<header class="header fixed clearfix">
		<div class="menu">
			<nav class="navbar navbar-default" role="navigation">
				<div class="collapse navbar-collapse  scrollspy smooth-scroll" id="navbar-collapse-1">
					<ul class="nav navbar-nav navbar-left">
						<li class="active">
							<a href="/home/" class="link-menu">INÍCIO</a>
						</li>
						{%if user.groups.all.0.name == 'Administrador' %}
						<li>
							<a class="link-menu" href="{% url 'restaurantes:restaurante_lista' %}">RESTAURANTES</a>
						</li>
						<li>
							<a class="link-menu" href="{% url 'comidas:comida_lista' %}">COMIDAS</a>
						</li>
						<li>
							<a href="#contato" class="link-menu" data-toggle="dropdown">RELATÓRIOS</a>
						</li>
						{%elif user.groups.all.0.name == 'Restaurante' %}
							<li>
								<a class="link-menu" href="{% url 'cardapios:cardapio_lista'%}">CARDÁPIO</a>
							</li>
							<li>
								<a class="link-menu" href="">PEDIDOS</a>
							</li>
						{%elif user.groups.all.0.name == 'Cliente' %}

						{%endif%}

					</ul>
				</div>
			</nav>
		</div>


    <div class="topo-login">
		<a class="btn" title="Sair do Sistema" href="/logout/"><i class="glyphicon glyphicon-off"></i>&nbsp;Sair</a>
    </div>
        


	</header>
    <div id="box">
        {%block content%}
		{%endblock%}	
    </div>



	<footer id="footer">
	</footer>
</body>
</html>

diskdelivery/core/templates/home.html
{% extends 'base.html' %}
{%block content%}

{{user}}


{%endblock%}

diskdelivery/core/templates/inicio_site.html
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">		
	<link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
	<link href="{{STATIC_URL}}css/style.css" rel="stylesheet">
	<link href="{{STATIC_URL}}css/topo.css" rel="stylesheet">


	<link href="{{ STATIC_URL }}css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	
	
	
	<link href="{{STATIC_URL}}css/principal.css" rel="stylesheet">
	
</head>

<body class="front scroll-spy">
	<header class="header fixed clearfix">
		<div class="col-md-4">
			<nav class="navbar navbar-default" role="navigation">
				<div class="collapse navbar-collapse  scrollspy smooth-scroll" id="navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="active">
							<a href="#home" class="link-menu">INÍCIO</a>
						</li>
						<li>
							<a href="#sobre" class="link-menu">RESTAURANTES</a>
						</li>
						<li>
							<a href="#contato" class="link-menu" data-toggle="dropdown">CONTATO</a>
						</li>
					</ul>
				</div>
			</nav>
		</div>


		<div class="col-md-1 topo-login">
			<nav class="navbar navbar-default" role="navigation">
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="" class="link-menu">Cadastre-se!</a>
					</li>
					<li class="active">
						<a href="/login/" class="link-menu">login</a>
					</li>
				</ul>
			</nav>
		</div>


	</header>
	<div id="box">
        {%block content%}
		{%endblock%}	
    </div>
	
	<footer id="footer">
	</footer>
</body>
</html>

diskdelivery/core/templates/login.html
<script src="{{ STATIC_URL }}js/jquery-2.0.0.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>        

<link href="{{ STATIC_URL }}css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" type="text/css"  />
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/login.css" />


<div class="container">
	<div class="login-container">
            <div id="output"></div>
            <div class="titulo">
                <h4>Disk Delívery =)</h4>
            </div>    
            <div class="form-box">
                <form action="" method="post">
                    {%csrf_token%}
                    {{form.username}}<br/>
                    {{form.password}}
                    <button class="btn btn-info btn-block login" type="submit">Entrar</button>
                </form>
            </div>
        </div>
</div>